services:
  flake-runner:
    image: vehicle-logic-descriptors
    volumes:
      - .:/app
    command: flake8

  app:
    image: vehicle-logic-descriptors
    volumes:
      - .:/app
    command: python main.py